Modified regex's to work on my system plus added `-q` to the `grep`'s to make output easier to read.

diff --git a/git-annex-remote-rclone b/git-annex-remote-rclone
--- a/git-annex-remote-rclone
+++ b/git-annex-remote-rclone
@@ -110,10 +110,10 @@ while read -r line; do
 			getconfig prefix
 			REMOTE_PREFIX=$RET
 			if [ -z "$REMOTE_PREFIX" ]; then
-                		REMOTE_PREFIX="git-annex"
+                REMOTE_PREFIX="git-annex"
 			fi
 			if [ "$REMOTE_PREFIX" == "/" ]; then
-		                echo INITREMOTE-FAILURE "storing objects directly in the root (/) is not supported"
+                echo INITREMOTE-FAILURE "storing objects directly in the root (/) is not supported"
 			fi
 			setconfig prefix $REMOTE_PREFIX
 
@@ -127,7 +127,7 @@ while read -r line; do
 			setconfig rclone_layout $RCLONE_LAYOUT
 
 			if [ -z "$REMOTE_TARGET" ]; then
-		                echo INITREMOTE-FAILURE "rclone remote target must be specified (use target= parameter)"
+                echo INITREMOTE-FAILURE "rclone remote target must be specified (use target= parameter)"
 			fi
 
             if runcmd rclone mkdir $REMOTE_TARGET:$REMOTE_PREFIX; then
@@ -198,16 +198,18 @@ while read -r line; do
 			# Any nonzero object count means present.
 			# Some rclone backends support multiple
 			# files under one name.
-			if check_result=$(rclone size "$LOC$key" 2>&1) &&
-			    echo $check_result|grep -E 'Total objects: [1-9][0-9]* Total size' >&2 &&
-			    ! echo $check_result|grep 'Total size: 0 (0 bytes)' >&2; then
-				echo CHECKPRESENT-SUCCESS "$key"
+            if check_result=$( (rclone size "$LOC$key") 2>&1)&&
+                  echo $check_result | grep -q -E 'Total objects: [1-9][0-9]* \([1-9][0-9]*\) Total size' >&2 &&
+                ! echo $check_result | grep -q -E 'Total size: 0(\s[^0-9]*)* \(0 (Byte|bytes)\)' >&2; 
+            then
+                echo CHECKPRESENT-SUCCESS "$key"
 			else
 				# rclone 1.29 used 'Total objects: 0'
 				# rclone 1.30 uses 'directory not found'
-				if echo $check_result|grep 'Total objects: 0' >&2 || 
-				   echo $check_result|grep ' directory not found' >&2; then 
-					echo CHECKPRESENT-FAILURE "$key"
+				if echo $check_result | grep -q 'Total objects: 0' >&2 || 
+				   echo $check_result | grep -q ' directory not found' >&2;
+                then 
+                    echo CHECKPRESENT-FAILURE "$key"
 				else
 					# When the directory does not exist,
 					# the remote is not available.
@@ -223,19 +225,20 @@ while read -r line; do
 			calclocation "$key"
 			# Note that it's not a failure to remove a
 			# key that is not present.
-			if remove_result=$(rclone delete --retries 1 "$LOC$key" 2>&1); then
-		                echo REMOVE-SUCCESS "$key"
-	                else
-	    		   	# rclone 1.29 used Failed to purge: Couldn't find directory:
-				# rclone 1.30 used no such file or directory
-				# rclone 1.33 uses directory not found
-		                if echo $remove_result | grep " Failed to purge: Couldn't find directory: " >&2 ||
-				   echo $remove_result | grep ' no such file or directory' ||
-				   echo $remove_result | grep ' directory not found' >&2
+            if remove_result=$( (rclone delete --retries 1 "$LOC$key") 2>&1); 
+            then
+                echo REMOVE-SUCCESS "$key"
+            else
+            # rclone 1.29 used Failed to purge: Couldn't find directory:
+            # rclone 1.30 used no such file or directory
+            # rclone 1.33 uses directory not found
+                if echo $remove_result | grep -q " Failed to purge: Couldn't find directory: " >&2 ||
+				   echo $remove_result | grep -q ' no such file or directory' >&2 ||
+				   echo $remove_result | grep -q ' directory not found' >&2
 				then   
 					echo REMOVE-SUCCESS "$key"
-		                else
-                		        echo REMOVE-FAILURE "$key"
+                else
+                    echo REMOVE-FAILURE "$key"
 				fi
 			fi
 		;;
